// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/predicate"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/processinstance"
)

// ProcessInstanceQuery is the builder for querying ProcessInstance entities.
type ProcessInstanceQuery struct {
	config
	ctx        *QueryContext
	order      []processinstance.OrderOption
	inters     []Interceptor
	predicates []predicate.ProcessInstance
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProcessInstanceQuery builder.
func (piq *ProcessInstanceQuery) Where(ps ...predicate.ProcessInstance) *ProcessInstanceQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *ProcessInstanceQuery) Limit(limit int) *ProcessInstanceQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *ProcessInstanceQuery) Offset(offset int) *ProcessInstanceQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *ProcessInstanceQuery) Unique(unique bool) *ProcessInstanceQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *ProcessInstanceQuery) Order(o ...processinstance.OrderOption) *ProcessInstanceQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// First returns the first ProcessInstance entity from the query.
// Returns a *NotFoundError when no ProcessInstance was found.
func (piq *ProcessInstanceQuery) First(ctx context.Context) (*ProcessInstance, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{processinstance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *ProcessInstanceQuery) FirstX(ctx context.Context) *ProcessInstance {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProcessInstance ID from the query.
// Returns a *NotFoundError when no ProcessInstance ID was found.
func (piq *ProcessInstanceQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{processinstance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *ProcessInstanceQuery) FirstIDX(ctx context.Context) int64 {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProcessInstance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProcessInstance entity is found.
// Returns a *NotFoundError when no ProcessInstance entities are found.
func (piq *ProcessInstanceQuery) Only(ctx context.Context) (*ProcessInstance, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{processinstance.Label}
	default:
		return nil, &NotSingularError{processinstance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *ProcessInstanceQuery) OnlyX(ctx context.Context) *ProcessInstance {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProcessInstance ID in the query.
// Returns a *NotSingularError when more than one ProcessInstance ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *ProcessInstanceQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{processinstance.Label}
	default:
		err = &NotSingularError{processinstance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *ProcessInstanceQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProcessInstances.
func (piq *ProcessInstanceQuery) All(ctx context.Context) ([]*ProcessInstance, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryAll)
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProcessInstance, *ProcessInstanceQuery]()
	return withInterceptors[[]*ProcessInstance](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *ProcessInstanceQuery) AllX(ctx context.Context) []*ProcessInstance {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProcessInstance IDs.
func (piq *ProcessInstanceQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryIDs)
	if err = piq.Select(processinstance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *ProcessInstanceQuery) IDsX(ctx context.Context) []int64 {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *ProcessInstanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryCount)
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*ProcessInstanceQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *ProcessInstanceQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *ProcessInstanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryExist)
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *ProcessInstanceQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProcessInstanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *ProcessInstanceQuery) Clone() *ProcessInstanceQuery {
	if piq == nil {
		return nil
	}
	return &ProcessInstanceQuery{
		config:     piq.config,
		ctx:        piq.ctx.Clone(),
		order:      append([]processinstance.OrderOption{}, piq.order...),
		inters:     append([]Interceptor{}, piq.inters...),
		predicates: append([]predicate.ProcessInstance{}, piq.predicates...),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BusinessKey string `json:"business_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProcessInstance.Query().
//		GroupBy(processinstance.FieldBusinessKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *ProcessInstanceQuery) GroupBy(field string, fields ...string) *ProcessInstanceGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProcessInstanceGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = processinstance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BusinessKey string `json:"business_key,omitempty"`
//	}
//
//	client.ProcessInstance.Query().
//		Select(processinstance.FieldBusinessKey).
//		Scan(ctx, &v)
func (piq *ProcessInstanceQuery) Select(fields ...string) *ProcessInstanceSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &ProcessInstanceSelect{ProcessInstanceQuery: piq}
	sbuild.label = processinstance.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProcessInstanceSelect configured with the given aggregations.
func (piq *ProcessInstanceQuery) Aggregate(fns ...AggregateFunc) *ProcessInstanceSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *ProcessInstanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !processinstance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *ProcessInstanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProcessInstance, error) {
	var (
		nodes = []*ProcessInstance{}
		_spec = piq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProcessInstance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProcessInstance{config: piq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (piq *ProcessInstanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *ProcessInstanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(processinstance.Table, processinstance.Columns, sqlgraph.NewFieldSpec(processinstance.FieldID, field.TypeInt64))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processinstance.FieldID)
		for i := range fields {
			if fields[i] != processinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *ProcessInstanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(processinstance.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = processinstance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProcessInstanceGroupBy is the group-by builder for ProcessInstance entities.
type ProcessInstanceGroupBy struct {
	selector
	build *ProcessInstanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *ProcessInstanceGroupBy) Aggregate(fns ...AggregateFunc) *ProcessInstanceGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *ProcessInstanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, ent.OpQueryGroupBy)
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcessInstanceQuery, *ProcessInstanceGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *ProcessInstanceGroupBy) sqlScan(ctx context.Context, root *ProcessInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProcessInstanceSelect is the builder for selecting fields of ProcessInstance entities.
type ProcessInstanceSelect struct {
	*ProcessInstanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *ProcessInstanceSelect) Aggregate(fns ...AggregateFunc) *ProcessInstanceSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *ProcessInstanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, ent.OpQuerySelect)
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcessInstanceQuery, *ProcessInstanceSelect](ctx, pis.ProcessInstanceQuery, pis, pis.inters, v)
}

func (pis *ProcessInstanceSelect) sqlScan(ctx context.Context, root *ProcessInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
