// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/workflow-engine/workflow-engine/internal/data/ent/historicprocessinstance"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/processdefinition"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/processevent"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/processinstance"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/processvariable"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/schema"
	"github.com/workflow-engine/workflow-engine/internal/data/ent/taskinstance"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	historicprocessinstanceFields := schema.HistoricProcessInstance{}.Fields()
	_ = historicprocessinstanceFields
	// historicprocessinstanceDescProcessInstanceID is the schema descriptor for process_instance_id field.
	historicprocessinstanceDescProcessInstanceID := historicprocessinstanceFields[1].Descriptor()
	// historicprocessinstance.ProcessInstanceIDValidator is a validator for the "process_instance_id" field. It is called by the builders before save.
	historicprocessinstance.ProcessInstanceIDValidator = func() func(string) error {
		validators := historicprocessinstanceDescProcessInstanceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(process_instance_id string) error {
			for _, fn := range fns {
				if err := fn(process_instance_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// historicprocessinstanceDescBusinessKey is the schema descriptor for business_key field.
	historicprocessinstanceDescBusinessKey := historicprocessinstanceFields[2].Descriptor()
	// historicprocessinstance.BusinessKeyValidator is a validator for the "business_key" field. It is called by the builders before save.
	historicprocessinstance.BusinessKeyValidator = historicprocessinstanceDescBusinessKey.Validators[0].(func(string) error)
	// historicprocessinstanceDescProcessDefinitionKey is the schema descriptor for process_definition_key field.
	historicprocessinstanceDescProcessDefinitionKey := historicprocessinstanceFields[4].Descriptor()
	// historicprocessinstance.ProcessDefinitionKeyValidator is a validator for the "process_definition_key" field. It is called by the builders before save.
	historicprocessinstance.ProcessDefinitionKeyValidator = func() func(string) error {
		validators := historicprocessinstanceDescProcessDefinitionKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(process_definition_key string) error {
			for _, fn := range fns {
				if err := fn(process_definition_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// historicprocessinstanceDescProcessDefinitionName is the schema descriptor for process_definition_name field.
	historicprocessinstanceDescProcessDefinitionName := historicprocessinstanceFields[5].Descriptor()
	// historicprocessinstance.ProcessDefinitionNameValidator is a validator for the "process_definition_name" field. It is called by the builders before save.
	historicprocessinstance.ProcessDefinitionNameValidator = historicprocessinstanceDescProcessDefinitionName.Validators[0].(func(string) error)
	// historicprocessinstanceDescDeploymentID is the schema descriptor for deployment_id field.
	historicprocessinstanceDescDeploymentID := historicprocessinstanceFields[7].Descriptor()
	// historicprocessinstance.DeploymentIDValidator is a validator for the "deployment_id" field. It is called by the builders before save.
	historicprocessinstance.DeploymentIDValidator = historicprocessinstanceDescDeploymentID.Validators[0].(func(string) error)
	// historicprocessinstanceDescStartUserID is the schema descriptor for start_user_id field.
	historicprocessinstanceDescStartUserID := historicprocessinstanceFields[8].Descriptor()
	// historicprocessinstance.StartUserIDValidator is a validator for the "start_user_id" field. It is called by the builders before save.
	historicprocessinstance.StartUserIDValidator = historicprocessinstanceDescStartUserID.Validators[0].(func(string) error)
	// historicprocessinstanceDescStartActivityID is the schema descriptor for start_activity_id field.
	historicprocessinstanceDescStartActivityID := historicprocessinstanceFields[12].Descriptor()
	// historicprocessinstance.StartActivityIDValidator is a validator for the "start_activity_id" field. It is called by the builders before save.
	historicprocessinstance.StartActivityIDValidator = historicprocessinstanceDescStartActivityID.Validators[0].(func(string) error)
	// historicprocessinstanceDescEndActivityID is the schema descriptor for end_activity_id field.
	historicprocessinstanceDescEndActivityID := historicprocessinstanceFields[13].Descriptor()
	// historicprocessinstance.EndActivityIDValidator is a validator for the "end_activity_id" field. It is called by the builders before save.
	historicprocessinstance.EndActivityIDValidator = historicprocessinstanceDescEndActivityID.Validators[0].(func(string) error)
	// historicprocessinstanceDescSuperProcessInstanceID is the schema descriptor for super_process_instance_id field.
	historicprocessinstanceDescSuperProcessInstanceID := historicprocessinstanceFields[14].Descriptor()
	// historicprocessinstance.SuperProcessInstanceIDValidator is a validator for the "super_process_instance_id" field. It is called by the builders before save.
	historicprocessinstance.SuperProcessInstanceIDValidator = historicprocessinstanceDescSuperProcessInstanceID.Validators[0].(func(string) error)
	// historicprocessinstanceDescRootProcessInstanceID is the schema descriptor for root_process_instance_id field.
	historicprocessinstanceDescRootProcessInstanceID := historicprocessinstanceFields[15].Descriptor()
	// historicprocessinstance.RootProcessInstanceIDValidator is a validator for the "root_process_instance_id" field. It is called by the builders before save.
	historicprocessinstance.RootProcessInstanceIDValidator = historicprocessinstanceDescRootProcessInstanceID.Validators[0].(func(string) error)
	// historicprocessinstanceDescSuperCaseInstanceID is the schema descriptor for super_case_instance_id field.
	historicprocessinstanceDescSuperCaseInstanceID := historicprocessinstanceFields[16].Descriptor()
	// historicprocessinstance.SuperCaseInstanceIDValidator is a validator for the "super_case_instance_id" field. It is called by the builders before save.
	historicprocessinstance.SuperCaseInstanceIDValidator = historicprocessinstanceDescSuperCaseInstanceID.Validators[0].(func(string) error)
	// historicprocessinstanceDescCaseInstanceID is the schema descriptor for case_instance_id field.
	historicprocessinstanceDescCaseInstanceID := historicprocessinstanceFields[17].Descriptor()
	// historicprocessinstance.CaseInstanceIDValidator is a validator for the "case_instance_id" field. It is called by the builders before save.
	historicprocessinstance.CaseInstanceIDValidator = historicprocessinstanceDescCaseInstanceID.Validators[0].(func(string) error)
	// historicprocessinstanceDescDeleteReason is the schema descriptor for delete_reason field.
	historicprocessinstanceDescDeleteReason := historicprocessinstanceFields[18].Descriptor()
	// historicprocessinstance.DeleteReasonValidator is a validator for the "delete_reason" field. It is called by the builders before save.
	historicprocessinstance.DeleteReasonValidator = historicprocessinstanceDescDeleteReason.Validators[0].(func(string) error)
	// historicprocessinstanceDescTenantID is the schema descriptor for tenant_id field.
	historicprocessinstanceDescTenantID := historicprocessinstanceFields[19].Descriptor()
	// historicprocessinstance.DefaultTenantID holds the default value on creation for the tenant_id field.
	historicprocessinstance.DefaultTenantID = historicprocessinstanceDescTenantID.Default.(string)
	// historicprocessinstance.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	historicprocessinstance.TenantIDValidator = historicprocessinstanceDescTenantID.Validators[0].(func(string) error)
	// historicprocessinstanceDescState is the schema descriptor for state field.
	historicprocessinstanceDescState := historicprocessinstanceFields[20].Descriptor()
	// historicprocessinstance.StateValidator is a validator for the "state" field. It is called by the builders before save.
	historicprocessinstance.StateValidator = historicprocessinstanceDescState.Validators[0].(func(string) error)
	// historicprocessinstanceDescRemovalTime is the schema descriptor for removal_time field.
	historicprocessinstanceDescRemovalTime := historicprocessinstanceFields[21].Descriptor()
	// historicprocessinstance.RemovalTimeValidator is a validator for the "removal_time" field. It is called by the builders before save.
	historicprocessinstance.RemovalTimeValidator = historicprocessinstanceDescRemovalTime.Validators[0].(func(string) error)
	// historicprocessinstanceDescCreatedAt is the schema descriptor for created_at field.
	historicprocessinstanceDescCreatedAt := historicprocessinstanceFields[22].Descriptor()
	// historicprocessinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	historicprocessinstance.DefaultCreatedAt = historicprocessinstanceDescCreatedAt.Default.(func() time.Time)
	// historicprocessinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	historicprocessinstanceDescUpdatedAt := historicprocessinstanceFields[23].Descriptor()
	// historicprocessinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	historicprocessinstance.DefaultUpdatedAt = historicprocessinstanceDescUpdatedAt.Default.(func() time.Time)
	// historicprocessinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	historicprocessinstance.UpdateDefaultUpdatedAt = historicprocessinstanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	processdefinitionFields := schema.ProcessDefinition{}.Fields()
	_ = processdefinitionFields
	// processdefinitionDescKey is the schema descriptor for key field.
	processdefinitionDescKey := processdefinitionFields[1].Descriptor()
	// processdefinition.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	processdefinition.KeyValidator = func() func(string) error {
		validators := processdefinitionDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// processdefinitionDescName is the schema descriptor for name field.
	processdefinitionDescName := processdefinitionFields[2].Descriptor()
	// processdefinition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	processdefinition.NameValidator = func() func(string) error {
		validators := processdefinitionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// processdefinitionDescCategory is the schema descriptor for category field.
	processdefinitionDescCategory := processdefinitionFields[3].Descriptor()
	// processdefinition.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	processdefinition.CategoryValidator = processdefinitionDescCategory.Validators[0].(func(string) error)
	// processdefinitionDescVersion is the schema descriptor for version field.
	processdefinitionDescVersion := processdefinitionFields[4].Descriptor()
	// processdefinition.DefaultVersion holds the default value on creation for the version field.
	processdefinition.DefaultVersion = processdefinitionDescVersion.Default.(int32)
	// processdefinitionDescDeployTime is the schema descriptor for deploy_time field.
	processdefinitionDescDeployTime := processdefinitionFields[6].Descriptor()
	// processdefinition.DefaultDeployTime holds the default value on creation for the deploy_time field.
	processdefinition.DefaultDeployTime = processdefinitionDescDeployTime.Default.(func() time.Time)
	// processdefinitionDescHasStartForm is the schema descriptor for has_start_form field.
	processdefinitionDescHasStartForm := processdefinitionFields[9].Descriptor()
	// processdefinition.DefaultHasStartForm holds the default value on creation for the has_start_form field.
	processdefinition.DefaultHasStartForm = processdefinitionDescHasStartForm.Default.(bool)
	// processdefinitionDescSuspended is the schema descriptor for suspended field.
	processdefinitionDescSuspended := processdefinitionFields[10].Descriptor()
	// processdefinition.DefaultSuspended holds the default value on creation for the suspended field.
	processdefinition.DefaultSuspended = processdefinitionDescSuspended.Default.(bool)
	// processdefinitionDescTenantID is the schema descriptor for tenant_id field.
	processdefinitionDescTenantID := processdefinitionFields[11].Descriptor()
	// processdefinition.DefaultTenantID holds the default value on creation for the tenant_id field.
	processdefinition.DefaultTenantID = processdefinitionDescTenantID.Default.(string)
	// processdefinition.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	processdefinition.TenantIDValidator = processdefinitionDescTenantID.Validators[0].(func(string) error)
	// processdefinitionDescCreatedAt is the schema descriptor for created_at field.
	processdefinitionDescCreatedAt := processdefinitionFields[12].Descriptor()
	// processdefinition.DefaultCreatedAt holds the default value on creation for the created_at field.
	processdefinition.DefaultCreatedAt = processdefinitionDescCreatedAt.Default.(func() time.Time)
	// processdefinitionDescUpdatedAt is the schema descriptor for updated_at field.
	processdefinitionDescUpdatedAt := processdefinitionFields[13].Descriptor()
	// processdefinition.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	processdefinition.DefaultUpdatedAt = processdefinitionDescUpdatedAt.Default.(func() time.Time)
	// processdefinition.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	processdefinition.UpdateDefaultUpdatedAt = processdefinitionDescUpdatedAt.UpdateDefault.(func() time.Time)
	processeventFields := schema.ProcessEvent{}.Fields()
	_ = processeventFields
	// processeventDescEventType is the schema descriptor for event_type field.
	processeventDescEventType := processeventFields[1].Descriptor()
	// processevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	processevent.EventTypeValidator = func() func(string) error {
		validators := processeventDescEventType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_type string) error {
			for _, fn := range fns {
				if err := fn(event_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// processeventDescEventName is the schema descriptor for event_name field.
	processeventDescEventName := processeventFields[2].Descriptor()
	// processevent.EventNameValidator is a validator for the "event_name" field. It is called by the builders before save.
	processevent.EventNameValidator = processeventDescEventName.Validators[0].(func(string) error)
	// processeventDescExecutionID is the schema descriptor for execution_id field.
	processeventDescExecutionID := processeventFields[3].Descriptor()
	// processevent.ExecutionIDValidator is a validator for the "execution_id" field. It is called by the builders before save.
	processevent.ExecutionIDValidator = processeventDescExecutionID.Validators[0].(func(string) error)
	// processeventDescProcessDefinitionKey is the schema descriptor for process_definition_key field.
	processeventDescProcessDefinitionKey := processeventFields[6].Descriptor()
	// processevent.ProcessDefinitionKeyValidator is a validator for the "process_definition_key" field. It is called by the builders before save.
	processevent.ProcessDefinitionKeyValidator = processeventDescProcessDefinitionKey.Validators[0].(func(string) error)
	// processeventDescActivityID is the schema descriptor for activity_id field.
	processeventDescActivityID := processeventFields[8].Descriptor()
	// processevent.ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	processevent.ActivityIDValidator = processeventDescActivityID.Validators[0].(func(string) error)
	// processeventDescActivityName is the schema descriptor for activity_name field.
	processeventDescActivityName := processeventFields[9].Descriptor()
	// processevent.ActivityNameValidator is a validator for the "activity_name" field. It is called by the builders before save.
	processevent.ActivityNameValidator = processeventDescActivityName.Validators[0].(func(string) error)
	// processeventDescActivityType is the schema descriptor for activity_type field.
	processeventDescActivityType := processeventFields[10].Descriptor()
	// processevent.ActivityTypeValidator is a validator for the "activity_type" field. It is called by the builders before save.
	processevent.ActivityTypeValidator = processeventDescActivityType.Validators[0].(func(string) error)
	// processeventDescUserID is the schema descriptor for user_id field.
	processeventDescUserID := processeventFields[11].Descriptor()
	// processevent.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	processevent.UserIDValidator = processeventDescUserID.Validators[0].(func(string) error)
	// processeventDescTimestamp is the schema descriptor for timestamp field.
	processeventDescTimestamp := processeventFields[12].Descriptor()
	// processevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	processevent.DefaultTimestamp = processeventDescTimestamp.Default.(func() time.Time)
	// processeventDescCorrelationID is the schema descriptor for correlation_id field.
	processeventDescCorrelationID := processeventFields[14].Descriptor()
	// processevent.CorrelationIDValidator is a validator for the "correlation_id" field. It is called by the builders before save.
	processevent.CorrelationIDValidator = processeventDescCorrelationID.Validators[0].(func(string) error)
	// processeventDescMessageName is the schema descriptor for message_name field.
	processeventDescMessageName := processeventFields[15].Descriptor()
	// processevent.MessageNameValidator is a validator for the "message_name" field. It is called by the builders before save.
	processevent.MessageNameValidator = processeventDescMessageName.Validators[0].(func(string) error)
	// processeventDescSignalName is the schema descriptor for signal_name field.
	processeventDescSignalName := processeventFields[16].Descriptor()
	// processevent.SignalNameValidator is a validator for the "signal_name" field. It is called by the builders before save.
	processevent.SignalNameValidator = processeventDescSignalName.Validators[0].(func(string) error)
	// processeventDescJobID is the schema descriptor for job_id field.
	processeventDescJobID := processeventFields[17].Descriptor()
	// processevent.JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	processevent.JobIDValidator = processeventDescJobID.Validators[0].(func(string) error)
	// processeventDescJobType is the schema descriptor for job_type field.
	processeventDescJobType := processeventFields[18].Descriptor()
	// processevent.JobTypeValidator is a validator for the "job_type" field. It is called by the builders before save.
	processevent.JobTypeValidator = processeventDescJobType.Validators[0].(func(string) error)
	// processeventDescJobHandlerType is the schema descriptor for job_handler_type field.
	processeventDescJobHandlerType := processeventFields[19].Descriptor()
	// processevent.JobHandlerTypeValidator is a validator for the "job_handler_type" field. It is called by the builders before save.
	processevent.JobHandlerTypeValidator = processeventDescJobHandlerType.Validators[0].(func(string) error)
	// processeventDescTenantID is the schema descriptor for tenant_id field.
	processeventDescTenantID := processeventFields[20].Descriptor()
	// processevent.DefaultTenantID holds the default value on creation for the tenant_id field.
	processevent.DefaultTenantID = processeventDescTenantID.Default.(string)
	// processevent.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	processevent.TenantIDValidator = processeventDescTenantID.Validators[0].(func(string) error)
	// processeventDescDeploymentID is the schema descriptor for deployment_id field.
	processeventDescDeploymentID := processeventFields[21].Descriptor()
	// processevent.DeploymentIDValidator is a validator for the "deployment_id" field. It is called by the builders before save.
	processevent.DeploymentIDValidator = processeventDescDeploymentID.Validators[0].(func(string) error)
	// processeventDescSequenceCounter is the schema descriptor for sequence_counter field.
	processeventDescSequenceCounter := processeventFields[22].Descriptor()
	// processevent.SequenceCounterValidator is a validator for the "sequence_counter" field. It is called by the builders before save.
	processevent.SequenceCounterValidator = processeventDescSequenceCounter.Validators[0].(func(string) error)
	// processeventDescCreatedAt is the schema descriptor for created_at field.
	processeventDescCreatedAt := processeventFields[23].Descriptor()
	// processevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	processevent.DefaultCreatedAt = processeventDescCreatedAt.Default.(func() time.Time)
	processinstanceFields := schema.ProcessInstance{}.Fields()
	_ = processinstanceFields
	// processinstanceDescBusinessKey is the schema descriptor for business_key field.
	processinstanceDescBusinessKey := processinstanceFields[1].Descriptor()
	// processinstance.BusinessKeyValidator is a validator for the "business_key" field. It is called by the builders before save.
	processinstance.BusinessKeyValidator = processinstanceDescBusinessKey.Validators[0].(func(string) error)
	// processinstanceDescProcessDefinitionKey is the schema descriptor for process_definition_key field.
	processinstanceDescProcessDefinitionKey := processinstanceFields[3].Descriptor()
	// processinstance.ProcessDefinitionKeyValidator is a validator for the "process_definition_key" field. It is called by the builders before save.
	processinstance.ProcessDefinitionKeyValidator = func() func(string) error {
		validators := processinstanceDescProcessDefinitionKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(process_definition_key string) error {
			for _, fn := range fns {
				if err := fn(process_definition_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// processinstanceDescProcessDefinitionName is the schema descriptor for process_definition_name field.
	processinstanceDescProcessDefinitionName := processinstanceFields[4].Descriptor()
	// processinstance.ProcessDefinitionNameValidator is a validator for the "process_definition_name" field. It is called by the builders before save.
	processinstance.ProcessDefinitionNameValidator = processinstanceDescProcessDefinitionName.Validators[0].(func(string) error)
	// processinstanceDescDeploymentID is the schema descriptor for deployment_id field.
	processinstanceDescDeploymentID := processinstanceFields[6].Descriptor()
	// processinstance.DeploymentIDValidator is a validator for the "deployment_id" field. It is called by the builders before save.
	processinstance.DeploymentIDValidator = processinstanceDescDeploymentID.Validators[0].(func(string) error)
	// processinstanceDescStartUserID is the schema descriptor for start_user_id field.
	processinstanceDescStartUserID := processinstanceFields[7].Descriptor()
	// processinstance.StartUserIDValidator is a validator for the "start_user_id" field. It is called by the builders before save.
	processinstance.StartUserIDValidator = processinstanceDescStartUserID.Validators[0].(func(string) error)
	// processinstanceDescStartTime is the schema descriptor for start_time field.
	processinstanceDescStartTime := processinstanceFields[8].Descriptor()
	// processinstance.DefaultStartTime holds the default value on creation for the start_time field.
	processinstance.DefaultStartTime = processinstanceDescStartTime.Default.(func() time.Time)
	// processinstanceDescDeleteReason is the schema descriptor for delete_reason field.
	processinstanceDescDeleteReason := processinstanceFields[11].Descriptor()
	// processinstance.DeleteReasonValidator is a validator for the "delete_reason" field. It is called by the builders before save.
	processinstance.DeleteReasonValidator = processinstanceDescDeleteReason.Validators[0].(func(string) error)
	// processinstanceDescSuperProcessInstanceID is the schema descriptor for super_process_instance_id field.
	processinstanceDescSuperProcessInstanceID := processinstanceFields[12].Descriptor()
	// processinstance.SuperProcessInstanceIDValidator is a validator for the "super_process_instance_id" field. It is called by the builders before save.
	processinstance.SuperProcessInstanceIDValidator = processinstanceDescSuperProcessInstanceID.Validators[0].(func(string) error)
	// processinstanceDescRootProcessInstanceID is the schema descriptor for root_process_instance_id field.
	processinstanceDescRootProcessInstanceID := processinstanceFields[13].Descriptor()
	// processinstance.RootProcessInstanceIDValidator is a validator for the "root_process_instance_id" field. It is called by the builders before save.
	processinstance.RootProcessInstanceIDValidator = processinstanceDescRootProcessInstanceID.Validators[0].(func(string) error)
	// processinstanceDescSuspended is the schema descriptor for suspended field.
	processinstanceDescSuspended := processinstanceFields[14].Descriptor()
	// processinstance.DefaultSuspended holds the default value on creation for the suspended field.
	processinstance.DefaultSuspended = processinstanceDescSuspended.Default.(bool)
	// processinstanceDescTenantID is the schema descriptor for tenant_id field.
	processinstanceDescTenantID := processinstanceFields[15].Descriptor()
	// processinstance.DefaultTenantID holds the default value on creation for the tenant_id field.
	processinstance.DefaultTenantID = processinstanceDescTenantID.Default.(string)
	// processinstance.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	processinstance.TenantIDValidator = processinstanceDescTenantID.Validators[0].(func(string) error)
	// processinstanceDescName is the schema descriptor for name field.
	processinstanceDescName := processinstanceFields[16].Descriptor()
	// processinstance.NameValidator is a validator for the "name" field. It is called by the builders before save.
	processinstance.NameValidator = processinstanceDescName.Validators[0].(func(string) error)
	// processinstanceDescCallbackID is the schema descriptor for callback_id field.
	processinstanceDescCallbackID := processinstanceFields[18].Descriptor()
	// processinstance.CallbackIDValidator is a validator for the "callback_id" field. It is called by the builders before save.
	processinstance.CallbackIDValidator = processinstanceDescCallbackID.Validators[0].(func(string) error)
	// processinstanceDescCallbackType is the schema descriptor for callback_type field.
	processinstanceDescCallbackType := processinstanceFields[19].Descriptor()
	// processinstance.CallbackTypeValidator is a validator for the "callback_type" field. It is called by the builders before save.
	processinstance.CallbackTypeValidator = processinstanceDescCallbackType.Validators[0].(func(string) error)
	// processinstanceDescReferenceID is the schema descriptor for reference_id field.
	processinstanceDescReferenceID := processinstanceFields[20].Descriptor()
	// processinstance.ReferenceIDValidator is a validator for the "reference_id" field. It is called by the builders before save.
	processinstance.ReferenceIDValidator = processinstanceDescReferenceID.Validators[0].(func(string) error)
	// processinstanceDescReferenceType is the schema descriptor for reference_type field.
	processinstanceDescReferenceType := processinstanceFields[21].Descriptor()
	// processinstance.ReferenceTypeValidator is a validator for the "reference_type" field. It is called by the builders before save.
	processinstance.ReferenceTypeValidator = processinstanceDescReferenceType.Validators[0].(func(string) error)
	// processinstanceDescCreatedAt is the schema descriptor for created_at field.
	processinstanceDescCreatedAt := processinstanceFields[22].Descriptor()
	// processinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	processinstance.DefaultCreatedAt = processinstanceDescCreatedAt.Default.(func() time.Time)
	// processinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	processinstanceDescUpdatedAt := processinstanceFields[23].Descriptor()
	// processinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	processinstance.DefaultUpdatedAt = processinstanceDescUpdatedAt.Default.(func() time.Time)
	// processinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	processinstance.UpdateDefaultUpdatedAt = processinstanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	processvariableFields := schema.ProcessVariable{}.Fields()
	_ = processvariableFields
	// processvariableDescName is the schema descriptor for name field.
	processvariableDescName := processvariableFields[1].Descriptor()
	// processvariable.NameValidator is a validator for the "name" field. It is called by the builders before save.
	processvariable.NameValidator = func() func(string) error {
		validators := processvariableDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// processvariableDescType is the schema descriptor for type field.
	processvariableDescType := processvariableFields[2].Descriptor()
	// processvariable.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	processvariable.TypeValidator = func() func(string) error {
		validators := processvariableDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// processvariableDescExecutionID is the schema descriptor for execution_id field.
	processvariableDescExecutionID := processvariableFields[8].Descriptor()
	// processvariable.ExecutionIDValidator is a validator for the "execution_id" field. It is called by the builders before save.
	processvariable.ExecutionIDValidator = processvariableDescExecutionID.Validators[0].(func(string) error)
	// processvariableDescCaseExecutionID is the schema descriptor for case_execution_id field.
	processvariableDescCaseExecutionID := processvariableFields[11].Descriptor()
	// processvariable.CaseExecutionIDValidator is a validator for the "case_execution_id" field. It is called by the builders before save.
	processvariable.CaseExecutionIDValidator = processvariableDescCaseExecutionID.Validators[0].(func(string) error)
	// processvariableDescCaseInstanceID is the schema descriptor for case_instance_id field.
	processvariableDescCaseInstanceID := processvariableFields[12].Descriptor()
	// processvariable.CaseInstanceIDValidator is a validator for the "case_instance_id" field. It is called by the builders before save.
	processvariable.CaseInstanceIDValidator = processvariableDescCaseInstanceID.Validators[0].(func(string) error)
	// processvariableDescActivityInstanceID is the schema descriptor for activity_instance_id field.
	processvariableDescActivityInstanceID := processvariableFields[14].Descriptor()
	// processvariable.ActivityInstanceIDValidator is a validator for the "activity_instance_id" field. It is called by the builders before save.
	processvariable.ActivityInstanceIDValidator = processvariableDescActivityInstanceID.Validators[0].(func(string) error)
	// processvariableDescTenantID is the schema descriptor for tenant_id field.
	processvariableDescTenantID := processvariableFields[15].Descriptor()
	// processvariable.DefaultTenantID holds the default value on creation for the tenant_id field.
	processvariable.DefaultTenantID = processvariableDescTenantID.Default.(string)
	// processvariable.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	processvariable.TenantIDValidator = processvariableDescTenantID.Validators[0].(func(string) error)
	// processvariableDescSequenceCounter is the schema descriptor for sequence_counter field.
	processvariableDescSequenceCounter := processvariableFields[16].Descriptor()
	// processvariable.DefaultSequenceCounter holds the default value on creation for the sequence_counter field.
	processvariable.DefaultSequenceCounter = processvariableDescSequenceCounter.Default.(int32)
	// processvariableDescConcurrentLocal is the schema descriptor for concurrent_local field.
	processvariableDescConcurrentLocal := processvariableFields[17].Descriptor()
	// processvariable.DefaultConcurrentLocal holds the default value on creation for the concurrent_local field.
	processvariable.DefaultConcurrentLocal = processvariableDescConcurrentLocal.Default.(bool)
	// processvariableDescScopeID is the schema descriptor for scope_id field.
	processvariableDescScopeID := processvariableFields[18].Descriptor()
	// processvariable.ScopeIDValidator is a validator for the "scope_id" field. It is called by the builders before save.
	processvariable.ScopeIDValidator = processvariableDescScopeID.Validators[0].(func(string) error)
	// processvariableDescScopeType is the schema descriptor for scope_type field.
	processvariableDescScopeType := processvariableFields[19].Descriptor()
	// processvariable.ScopeTypeValidator is a validator for the "scope_type" field. It is called by the builders before save.
	processvariable.ScopeTypeValidator = processvariableDescScopeType.Validators[0].(func(string) error)
	// processvariableDescCreatedAt is the schema descriptor for created_at field.
	processvariableDescCreatedAt := processvariableFields[20].Descriptor()
	// processvariable.DefaultCreatedAt holds the default value on creation for the created_at field.
	processvariable.DefaultCreatedAt = processvariableDescCreatedAt.Default.(func() time.Time)
	// processvariableDescUpdatedAt is the schema descriptor for updated_at field.
	processvariableDescUpdatedAt := processvariableFields[21].Descriptor()
	// processvariable.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	processvariable.DefaultUpdatedAt = processvariableDescUpdatedAt.Default.(func() time.Time)
	// processvariable.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	processvariable.UpdateDefaultUpdatedAt = processvariableDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskinstanceFields := schema.TaskInstance{}.Fields()
	_ = taskinstanceFields
	// taskinstanceDescName is the schema descriptor for name field.
	taskinstanceDescName := taskinstanceFields[1].Descriptor()
	// taskinstance.NameValidator is a validator for the "name" field. It is called by the builders before save.
	taskinstance.NameValidator = taskinstanceDescName.Validators[0].(func(string) error)
	// taskinstanceDescTaskDefinitionKey is the schema descriptor for task_definition_key field.
	taskinstanceDescTaskDefinitionKey := taskinstanceFields[3].Descriptor()
	// taskinstance.TaskDefinitionKeyValidator is a validator for the "task_definition_key" field. It is called by the builders before save.
	taskinstance.TaskDefinitionKeyValidator = func() func(string) error {
		validators := taskinstanceDescTaskDefinitionKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(task_definition_key string) error {
			for _, fn := range fns {
				if err := fn(task_definition_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskinstanceDescAssignee is the schema descriptor for assignee field.
	taskinstanceDescAssignee := taskinstanceFields[4].Descriptor()
	// taskinstance.AssigneeValidator is a validator for the "assignee" field. It is called by the builders before save.
	taskinstance.AssigneeValidator = taskinstanceDescAssignee.Validators[0].(func(string) error)
	// taskinstanceDescOwner is the schema descriptor for owner field.
	taskinstanceDescOwner := taskinstanceFields[5].Descriptor()
	// taskinstance.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	taskinstance.OwnerValidator = taskinstanceDescOwner.Validators[0].(func(string) error)
	// taskinstanceDescDelegation is the schema descriptor for delegation field.
	taskinstanceDescDelegation := taskinstanceFields[6].Descriptor()
	// taskinstance.DelegationValidator is a validator for the "delegation" field. It is called by the builders before save.
	taskinstance.DelegationValidator = taskinstanceDescDelegation.Validators[0].(func(string) error)
	// taskinstanceDescPriority is the schema descriptor for priority field.
	taskinstanceDescPriority := taskinstanceFields[7].Descriptor()
	// taskinstance.DefaultPriority holds the default value on creation for the priority field.
	taskinstance.DefaultPriority = taskinstanceDescPriority.Default.(int32)
	// taskinstanceDescCreateTime is the schema descriptor for create_time field.
	taskinstanceDescCreateTime := taskinstanceFields[8].Descriptor()
	// taskinstance.DefaultCreateTime holds the default value on creation for the create_time field.
	taskinstance.DefaultCreateTime = taskinstanceDescCreateTime.Default.(func() time.Time)
	// taskinstanceDescFormKey is the schema descriptor for form_key field.
	taskinstanceDescFormKey := taskinstanceFields[11].Descriptor()
	// taskinstance.FormKeyValidator is a validator for the "form_key" field. It is called by the builders before save.
	taskinstance.FormKeyValidator = taskinstanceDescFormKey.Validators[0].(func(string) error)
	// taskinstanceDescCategory is the schema descriptor for category field.
	taskinstanceDescCategory := taskinstanceFields[12].Descriptor()
	// taskinstance.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	taskinstance.CategoryValidator = taskinstanceDescCategory.Validators[0].(func(string) error)
	// taskinstanceDescParentTaskID is the schema descriptor for parent_task_id field.
	taskinstanceDescParentTaskID := taskinstanceFields[13].Descriptor()
	// taskinstance.ParentTaskIDValidator is a validator for the "parent_task_id" field. It is called by the builders before save.
	taskinstance.ParentTaskIDValidator = taskinstanceDescParentTaskID.Validators[0].(func(string) error)
	// taskinstanceDescExecutionID is the schema descriptor for execution_id field.
	taskinstanceDescExecutionID := taskinstanceFields[14].Descriptor()
	// taskinstance.ExecutionIDValidator is a validator for the "execution_id" field. It is called by the builders before save.
	taskinstance.ExecutionIDValidator = taskinstanceDescExecutionID.Validators[0].(func(string) error)
	// taskinstanceDescProcessDefinitionKey is the schema descriptor for process_definition_key field.
	taskinstanceDescProcessDefinitionKey := taskinstanceFields[17].Descriptor()
	// taskinstance.ProcessDefinitionKeyValidator is a validator for the "process_definition_key" field. It is called by the builders before save.
	taskinstance.ProcessDefinitionKeyValidator = func() func(string) error {
		validators := taskinstanceDescProcessDefinitionKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(process_definition_key string) error {
			for _, fn := range fns {
				if err := fn(process_definition_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskinstanceDescCaseExecutionID is the schema descriptor for case_execution_id field.
	taskinstanceDescCaseExecutionID := taskinstanceFields[18].Descriptor()
	// taskinstance.CaseExecutionIDValidator is a validator for the "case_execution_id" field. It is called by the builders before save.
	taskinstance.CaseExecutionIDValidator = taskinstanceDescCaseExecutionID.Validators[0].(func(string) error)
	// taskinstanceDescCaseInstanceID is the schema descriptor for case_instance_id field.
	taskinstanceDescCaseInstanceID := taskinstanceFields[19].Descriptor()
	// taskinstance.CaseInstanceIDValidator is a validator for the "case_instance_id" field. It is called by the builders before save.
	taskinstance.CaseInstanceIDValidator = taskinstanceDescCaseInstanceID.Validators[0].(func(string) error)
	// taskinstanceDescCaseDefinitionID is the schema descriptor for case_definition_id field.
	taskinstanceDescCaseDefinitionID := taskinstanceFields[20].Descriptor()
	// taskinstance.CaseDefinitionIDValidator is a validator for the "case_definition_id" field. It is called by the builders before save.
	taskinstance.CaseDefinitionIDValidator = taskinstanceDescCaseDefinitionID.Validators[0].(func(string) error)
	// taskinstanceDescSuspended is the schema descriptor for suspended field.
	taskinstanceDescSuspended := taskinstanceFields[21].Descriptor()
	// taskinstance.DefaultSuspended holds the default value on creation for the suspended field.
	taskinstance.DefaultSuspended = taskinstanceDescSuspended.Default.(bool)
	// taskinstanceDescTenantID is the schema descriptor for tenant_id field.
	taskinstanceDescTenantID := taskinstanceFields[22].Descriptor()
	// taskinstance.DefaultTenantID holds the default value on creation for the tenant_id field.
	taskinstance.DefaultTenantID = taskinstanceDescTenantID.Default.(string)
	// taskinstance.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	taskinstance.TenantIDValidator = taskinstanceDescTenantID.Validators[0].(func(string) error)
	// taskinstanceDescCreatedAt is the schema descriptor for created_at field.
	taskinstanceDescCreatedAt := taskinstanceFields[23].Descriptor()
	// taskinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	taskinstance.DefaultCreatedAt = taskinstanceDescCreatedAt.Default.(func() time.Time)
	// taskinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	taskinstanceDescUpdatedAt := taskinstanceFields[24].Descriptor()
	// taskinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	taskinstance.DefaultUpdatedAt = taskinstanceDescUpdatedAt.Default.(func() time.Time)
	// taskinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	taskinstance.UpdateDefaultUpdatedAt = taskinstanceDescUpdatedAt.UpdateDefault.(func() time.Time)
}
