# 数据库配置
# 支持多环境的数据库连接配置
database:
  # PostgreSQL 主数据库配置
  postgres:
    host: localhost
    port: 5432
    database: workflow_engine
    username: postgres
    password: postgres
    sslmode: disable
    max_open_conns: 50 # 最大打开连接数
    max_idle_conns: 10 # 最大空闲连接数
    conn_max_lifetime: 300s # 连接最大生存时间
    conn_max_idle_time: 60s # 连接最大空闲时间

  # Redis 缓存配置
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 0
    max_retries: 3
    pool_size: 10
    pool_timeout: 30s
    idle_timeout: 300s

  # 迁移配置
  migration:
    source: "file://migrations"
    table: schema_migrations
    lock_timeout: 15m
    force_version: false # 是否强制版本

# 环境特定配置
environments:
  # 开发环境
  development:
    postgres:
      host: localhost
      port: 5432
      database: workflow_engine_dev
      username: postgres
      password: postgres
      sslmode: disable
      max_open_conns: 10
      max_idle_conns: 5
      log_level: debug

    redis:
      host: localhost
      port: 6379
      database: 1

  # 测试环境
  test:
    postgres:
      host: localhost
      port: 5432
      database: workflow_engine_test
      username: postgres
      password: postgres
      sslmode: disable
      max_open_conns: 5
      max_idle_conns: 2
      log_level: warn

    redis:
      host: localhost
      port: 6379
      database: 2

  # 生产环境
  production:
    postgres:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT:5432}
      database: ${DATABASE_NAME}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      sslmode: ${DATABASE_SSL_MODE:require}
      max_open_conns: 100
      max_idle_conns: 20
      conn_max_lifetime: 600s
      log_level: error

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB:0}
      pool_size: 20

# 健康检查配置
health_check:
  enabled: true
  interval: 30s
  timeout: 5s
  postgres:
    enabled: true
    query: "SELECT 1"
  redis:
    enabled: true
    ping_timeout: 1s
