# Prometheus 配置文件
# 监控工作流引擎各组件的性能指标
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "workflow-engine"
    environment: "production"

# 告警规则文件
rule_files:
  - "rules/*.yml"

# 服务发现和抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Workflow Engine 应用监控
  - job_name: "workflow-engine"
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - workflow-engine
    relabel_configs:
      # 只抓取有prometheus.io/scrape注解的Pod
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # 使用prometheus.io/path注解指定metrics路径
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # 使用prometheus.io/port注解指定端口
      - source_labels:
          [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      # 添加Pod标签
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      # 添加namespace标签
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      # 添加pod名称标签
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
    scrape_interval: 10s
    metrics_path: "/metrics"

  # PostgreSQL 数据库监控
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-service:5432"]
    scrape_interval: 30s
    params:
      format: ["prometheus"]

  # Redis 缓存监控
  - job_name: "redis"
    static_configs:
      - targets: ["redis-service:6379"]
    scrape_interval: 30s

  # Temporal 工作流引擎监控
  - job_name: "temporal"
    static_configs:
      - targets: ["temporal-service:7233"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  # Kubernetes 节点监控
  - job_name: "kubernetes-nodes"
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pod 监控
  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels:
          [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # cAdvisor 容器监控
  - job_name: "kubernetes-cadvisor"
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
# 远程写入配置 (可选)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.example.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# 远程读取配置 (可选)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.example.com/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"
